#!/bin/bash
# Script requires java executable to be already provided in the shell

SCRIPT_DIR="$(cd "$( dirname "$0" )" && pwd)"

java -cp "$SCRIPT_DIR/../lib/my-vault/*" \
  org.goffi.my.vault.gui.App "$@"
